version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
  
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  nginx:
    container_name: nginx
    build:
      context: ./frontend
    restart: always
    ports:
      - "80:80"

volumes:
  dbdata:
